name: AltEconomy
version: 0.0.0.005
description: AltEcononmy
main: main.java.ru.altspace.AltEconomy
authors: [AltSpace]
commands:
  cur:
    permission: alteconomy.cur
    permission-message: You dont have permissions!
  pay:
    permission: alteconomy.pay
    permission-message: You dont have permissions!
    usage: /pay [player] [currencyType] [value]
  curlist:
    permission: alteconomy.curlist
    permission-message: You dont have permissions!

